### ISSUE TITLE
Change the metadata

### ISSUE THREAD

**Issue by flaviocopes** [MaZderMind/grav-plugin-urlparamfilter#1]
Please change https://github.com/MaZderMind/grav-plugin-urlparamfilter/blob/master/blueprints.yaml as it's listing the Login plugin information, showing up wrong in https://getgrav.org/downloads/plugins

**Comment by flaviocopes** [comment]
Also, the form definition is not relevant to the plugin, you might want to remove it altogether if you have no settings (except for `enable`)

**Comment by MaZderMind** [comment]
Oops, sorry, will do that asap.

**Comment by flaviocopes** [comment]
👍 

We removed the plugin from the list to avoid confusion, open a ticket on Grav to re-enable it when you'll release an update.
